### ISSUE TITLE
Week 10 - Links are not working

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#52]
Hi **Susan**,

 Please check the links in the notes for *Create add a book*, I am getting 404 error for *Relevant Files*-

 
![image](https://user-images.githubusercontent.com/64241541/162801528-d1276565-df08-4496-93a1-41155b6ae603.png)

**Comment by susanBuck** [comment]
Fixed 👍

**Comment by mgarimelHES** [comment]
I dont know why I am still getting the 404 -


![image](https://user-images.githubusercontent.com/64241541/162817219-335b339e-9adb-4903-b9ea-d230b0c5117e.png)

**Comment by susanBuck** [comment]
Apologies - I made the changes locally but forgot to deploy them to production. _Now_ it should be fixed. : )

FYI these code files can be found manually by looking through my e15 code repository: https://github.com/susanBuck/e15

**Comment by mgarimelHES** [comment]
No problem, thanks for looking into it. Appreciate it.
